services:
  db:
    image: mariadb:10.11
    environment:
      MYSQL_DATABASE: wp1
      MYSQL_ROOT_PASSWORD: password1
    networks:
      - db1-net

  wordpress:
    image: wordpress:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wp1.rule=Host(`site1.local`)"
      - "traefik.http.routers.wp1.entrypoints=websecure"
      - "traefik.http.routers.wp1.tls.certresolver=myresolver"
    networks:
      - db1-net
      - traefik-net

networks:
  db1-net:
  traefik-net:
    external: true